language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm
        - php: hhvm-nightly

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source
    - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then FLAGS="-d extension=xdebug.so --coverage coverage.xml --coverage-src src"; fi;

script:
    - vendor/bin/tester -p php tests -s $FLAGS

after_script:
    - |
        if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
            wget https://scrutinizer-ci.com/ocular.phar
            php ocular.phar code-coverage:upload --format=php-clover coverage.xml
        fi

after_failure:
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
